name: Publish Dev Container Feature
on:
  push:
    tags: ['v*']

permissions:
  contents: read
  packages: write   # GHCR へ publish に必須

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish feature(s)
        uses: devcontainers/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ← これが肝
        with:
          publish-features: true
          base-path-to-features: ./src
          # registries: ghcr.io        # 省略可（既定 ghcr.io）
          # namespace: asobod11138/devcontainer-features  # 省略可（既定：<owner>/<repo>）
